"""create initial schema

Revision ID: 297a889455af
Revises: 
Create Date: 2026-08-06 16:47:20.201227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '297a889455af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_environments'))
    )
    op.create_index(op.f('ix_environments_slug'), 'environments', ['slug'], unique=True)
    op.create_table('applications',
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('method', sa.Enum('GET', 'HEAD', name='http_method'), nullable=False),
    sa.Column('expected_status_code', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('check_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], name=op.f('fk_applications_environment_id_environments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('environment_id', 'slug', name='uq_environment_application_slug')
    )
    op.create_index(op.f('ix_applications_environment_id'), 'applications', ['environment_id'], unique=False)
    op.create_index(op.f('ix_applications_is_active'), 'applications', ['is_active'], unique=False)
    op.create_table('health_checks',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('UP', 'DOWN', name='health_status'), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_health_checks_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_health_checks'))
    )
    op.create_index(op.f('ix_health_checks_application_id'), 'health_checks', ['application_id'], unique=False)
    op.create_index(op.f('ix_health_checks_checked_at'), 'health_checks', ['checked_at'], unique=False)
    op.create_index(op.f('ix_health_checks_status'), 'health_checks', ['status'], unique=False)
    op.create_table('incidents',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', name='incident_status'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_incidents_application_id_applications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incidents'))
    )
    op.create_index(op.f('ix_incidents_application_id'), 'incidents', ['application_id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_application_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_health_checks_status'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_checked_at'), table_name='health_checks')
    op.drop_index(op.f('ix_health_checks_application_id'), table_name='health_checks')
    op.drop_table('health_checks')
    op.drop_index(op.f('ix_applications_is_active'), table_name='applications')
    op.drop_index(op.f('ix_applications_environment_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_environments_slug'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
